diff --git a/Makefile b/Makefile
index 0d0865188..abd1b75fb 100755
--- a/Makefile
+++ b/Makefile
@@ -176,7 +176,7 @@ integration: out/minikube
 
 .PHONY: integration-none-driver
 integration-none-driver: e2e-linux-$(GOARCH) out/minikube-linux-$(GOARCH)
-	sudo -E out/e2e-linux-$(GOARCH) -testdata-dir "test/integration/testdata" -minikube-start-args="--vm-driver=none" -test.v -test.timeout=60m -binary=out/minikube-linux-amd64 $(TEST_ARGS)
+	sudo -E out/e2e-linux-$(GOARCH) -testdata-dir "test/integration/testdata" -minikube-start-args="--vm-driver=none" -test.v -test.timeout=60m -binary=out/minikube-linux-s390x $(TEST_ARGS)
 
 .PHONY: integration-versioned
 integration-versioned: out/minikube
@@ -262,16 +262,16 @@ mdlint:
 out/docs/minikube.md: $(shell find cmd) $(shell find pkg/minikube/constants) pkg/minikube/assets/assets.go
 	go run -ldflags="$(MINIKUBE_LDFLAGS)" hack/help_text/gen_help_text.go
 
-out/minikube_$(DEB_VERSION).deb: out/minikube-linux-amd64
+out/minikube_$(DEB_VERSION).deb: out/minikube-linux-s390x
 	cp -r installers/linux/deb/minikube_deb_template out/minikube_$(DEB_VERSION)
 	chmod 0755 out/minikube_$(DEB_VERSION)/DEBIAN
 	sed -E -i 's/--VERSION--/'$(DEB_VERSION)'/g' out/minikube_$(DEB_VERSION)/DEBIAN/control
 	mkdir -p out/minikube_$(DEB_VERSION)/usr/bin
-	cp out/minikube-linux-amd64 out/minikube_$(DEB_VERSION)/usr/bin/minikube
+	cp out/minikube-linux-s390x out/minikube_$(DEB_VERSION)/usr/bin/minikube
 	fakeroot dpkg-deb --build out/minikube_$(DEB_VERSION)
 	rm -rf out/minikube_$(DEB_VERSION)
 
-out/minikube-$(RPM_VERSION).rpm: out/minikube-linux-amd64
+out/minikube-$(RPM_VERSION).rpm: out/minikube-linux-s390x
 	cp -r installers/linux/rpm/minikube_rpm_template out/minikube-$(RPM_VERSION)
 	sed -E -i 's/--VERSION--/'$(RPM_VERSION)'/g' out/minikube-$(RPM_VERSION)/minikube.spec
 	sed -E -i 's|--OUT--|'$(PWD)/out'|g' out/minikube-$(RPM_VERSION)/minikube.spec
@@ -280,15 +280,15 @@ out/minikube-$(RPM_VERSION).rpm: out/minikube-linux-amd64
 	rm -rf out/minikube-$(RPM_VERSION)
 
 .SECONDEXPANSION:
-TAR_TARGETS_linux   := out/minikube-linux-amd64 out/docker-machine-driver-kvm2
+TAR_TARGETS_linux   := out/minikube-linux-s390x out/docker-machine-driver-kvm2
 TAR_TARGETS_darwin  := out/minikube-darwin-amd64
 TAR_TARGETS_windows := out/minikube-windows-amd64.exe
 TAR_TARGETS_ALL     := $(shell find deploy/addons -type f)
-out/minikube-%-amd64.tar.gz: $$(TAR_TARGETS_$$*) $(TAR_TARGETS_ALL)
+out/minikube-%-s390x.tar.gz: $$(TAR_TARGETS_$$*) $(TAR_TARGETS_ALL)
 	tar -cvf $@ $^
 
 .PHONY: cross-tars
-cross-tars: kvm_in_docker out/minikube-windows-amd64.tar.gz out/minikube-linux-amd64.tar.gz out/minikube-darwin-amd64.tar.gz
+cross-tars: kvm_in_docker out/minikube-windows-amd64.tar.gz out/minikube-linux-s390x.tar.gz out/minikube-darwin-amd64.tar.gz
 
 out/minikube-installer.exe: out/minikube-windows-amd64.exe
 	rm -rf out/windows_tmp
